-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.title
(
    title_name text
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id integer NOT NULL,
    customer_name text,
    produckt_name text,
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    id integer NOT NULL,
    fullname text,
    age integer,
    team text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.team
(
    team_name text NOT NULL,
    product text NOT NULL,
    PRIMARY KEY (team_name)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_name text NOT NULL,
    product_id integer NOT NULL,
    PRIMARY KEY (product_id)
);

ALTER TABLE IF EXISTS public.customers
    ADD FOREIGN KEY (produckt_name)
    REFERENCES public.team (product) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT title FOREIGN KEY (title)
    REFERENCES public.title (title_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT team FOREIGN KEY (team)
    REFERENCES public.team (team_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team
    ADD CONSTRAINT product FOREIGN KEY (product)
    REFERENCES public.products (product_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team
    ADD CONSTRAINT customer FOREIGN KEY (product)
    REFERENCES public.customers (produckt_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT aa FOREIGN KEY (product_name)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;