-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employee
(
    employee_id integer NOT NULL,
    employee_name cstring[] NOT NULL,
    employee_surname cstring[] NOT NULL,
    title_id cstring[] NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public.title
(
    title_id integer NOT NULL,
    title_name cstring[] NOT NULL,
    PRIMARY KEY (title_id)
);

CREATE TABLE IF NOT EXISTS public.team
(
    team_id integer NOT NULL,
    team_name cstring[] NOT NULL,
    employee_id cstring[] NOT NULL,
    product_id cstring[] NOT NULL,
    PRIMARY KEY (team_id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    customer_id integer NOT NULL,
    customer_name cstring[] NOT NULL,
    customer_address cstring[] NOT NULL,
    product_id integer NOT NULL,
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL,
    product_name cstring[] NOT NULL,
    customer_id cstring[] NOT NULL,
    PRIMARY KEY (product_id)
);

ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (title_id)
    REFERENCES public.title (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (title_id)
    REFERENCES public.title (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;