-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customer"
(
    c_id integer NOT NULL,
    c_name text COLLATE pg_catalog."default",
    CONSTRAINT "Customer_pkey" PRIMARY KEY (c_id)
);

CREATE TABLE IF NOT EXISTS public."Departments"
(
    d_id integer NOT NULL,
    title text COLLATE pg_catalog."default",
    CONSTRAINT "Departments_pkey" PRIMARY KEY (d_id)
);

CREATE TABLE IF NOT EXISTS public."Employees"
(
    e_id integer NOT NULL,
    fullname text COLLATE pg_catalog."default",
    salary integer,
    department_id integer,
    CONSTRAINT "Employees_pkey" PRIMARY KEY (e_id)
);

CREATE TABLE IF NOT EXISTS public."Products"
(
    p_id integer NOT NULL,
    p_name text COLLATE pg_catalog."default",
    customer_id integer,
    departmentt_id integer,
    price integer,
    start_date integer,
    end_date integer,
    status_id integer,
    CONSTRAINT "Products_pkey" PRIMARY KEY (p_id)
);

CREATE TABLE IF NOT EXISTS public."Status"
(
    s_id integer NOT NULL,
    s_name text COLLATE pg_catalog."default",
    CONSTRAINT "Status_pkey" PRIMARY KEY (s_id)
);

ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT "Employees_department_id_fkey" FOREIGN KEY (department_id)
    REFERENCES public."Departments" (d_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Products"
    ADD CONSTRAINT "Products_customer_id_fkey" FOREIGN KEY (customer_id)
    REFERENCES public."Customer" (c_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Products"
    ADD CONSTRAINT "Products_departmentt_id_fkey" FOREIGN KEY (departmentt_id)
    REFERENCES public."Departments" (d_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Products"
    ADD CONSTRAINT "Products_status_id_fkey" FOREIGN KEY (status_id)
    REFERENCES public."Status" (s_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;